(define (problem prob_bw_5_n5_es6_r506)
  (:domain prob_bw)
  (:objects b1 b2 b3 b4 b5 - block)
  (:init (emptyhand) (on b1 b4) (on-table b2) (on b3 b1) (on-table b4) (on b5 b3) (clear b2) (clear b5))
  (:goal (and (emptyhand) (on-table b1) (on b2 b4) (on b3 b2) (on b4 b5) (on-table b5) (clear b1) (clear b3)))
)
