(define (problem prob_bw_4_n4_es5_r405)
  (:domain prob_bw)
  (:objects b1 b2 b3 b4 - block)
  (:init (emptyhand) (on b1 b4) (on-table b2) (on-table b3) (on b4 b3) (clear b1) (clear b2))
  (:goal (and (emptyhand) (on-table b1) (on-table b2) (on-table b3) (on b4 b2) (clear b1) (clear b3) (clear b4)))
)
