(define (problem prob_bw_5_n5_es3_r503)
  (:domain prob_bw)
  (:objects b1 b2 b3 b4 b5 - block)
  (:init (emptyhand) (on b1 b3) (on-table b2) (on b3 b4) (on-table b4) (on-table b5) (clear b1) (clear b2) (clear b5))
  (:goal (and (emptyhand) (on-table b1) (on b2 b5) (on-table b3) (on b4 b3) (on b5 b1) (clear b2) (clear b4)))
)
