(define (problem prob_bw_6_n6_es4_r604)
  (:domain prob_bw)
  (:objects b1 b2 b3 b4 b5 b6 - block)
  (:init (emptyhand) (on b1 b6) (on b2 b5) (on-table b3) (on-table b4) (on-table b5) (on-table b6) (clear b1) (clear b2) (clear b3) (clear b4))
  (:goal (and (emptyhand) (on-table b1) (on-table b2) (on b3 b2) (on-table b4) (on b5 b4) (on b6 b5) (clear b1) (clear b3) (clear b6)))
)
