(define (problem ex_bw_4_tiny)
  (:domain exploding-blocksworld)
  (:objects b1 b2 b3 b4 - block)
  (:init (emptyhand) (on-table b1) (on b2 b3) (on b3 b4) (on b4 b1) (clear b2) (no-detonated b1) (no-destroyed b1) (no-detonated b2) (no-destroyed b2) (no-detonated b3) (no-destroyed b3) (no-detonated b4) (no-destroyed b4) (no-destroyed-table))
  (:goal (and (on-table b1) (on b2 b3) (on b3 b1) (on-table b4)  )
)
  (:goal-reward 1)
  (:metric maximize (reward))
)
