(define (problem descent-n6-s1)
  (:domain descent)
  (:objects l0 l1 l2 l3 l4 l5 - location)
  (:init (at l0) (alive) (have-rope)
    (descent l0 l1)
    (descent l1 l2)
    (descent l1 l3)
    (descent l1 l4)
    (descent l2 l4)
    (descent l2 l5)
    (descent l3 l4)
    (descent l4 l5)
  )
  (:goal (and (at l5) (alive)))
)
