(define (problem descent-n8-s1)
  (:domain descent)
  (:objects l0 l1 l2 l3 l4 l5 l6 l7 - location)
  (:init (at l0) (alive) (have-rope)
    (descent l0 l1)
    (descent l0 l3)
    (descent l1 l2)
    (descent l1 l4)
    (descent l2 l3)
    (descent l2 l4)
    (descent l3 l4)
    (descent l3 l5)
    (descent l3 l6)
    (descent l4 l5)
    (descent l4 l6)
    (descent l4 l7)
    (descent l5 l6)
    (descent l5 l7)
    (descent l6 l7)
  )
  (:goal (and (at l7) (alive)))
)
