(define (problem descent-n5-s1)
  (:domain descent)
  (:objects l0 l1 l2 l3 l4 - location)
  (:init (at l0) (alive) (have-rope)
    (descent l0 l1)
    (descent l0 l2)
    (descent l0 l3)
    (descent l1 l3)
    (descent l2 l4)
    (descent l3 l4)
  )
  (:goal (and (at l4) (alive)))
)
