(define (problem descent-n3-s1)
  (:domain descent)
  (:objects l0 l1 l2 - location)
  (:init (at l0) (alive) (have-rope)
    (descent l0 l1)
    (descent l0 l2)
    (descent l1 l2)
  )
  (:goal (and (at l2) (alive)))
)
