(define (problem rect-5-5-2-2-1)
  (:domain rectangle-world)
  (:objects n0 n1 n2 n3 n4 - int)
  (:init (xpos n0)
	 (ypos n0)
         (next n0 n1)
         (next n1 n2)
         (next n2 n3)
         (next n3 n4)
	 (safeX n1)
	 (safeX n3)
	 (safeY n0)
	 (safeY n2)
  )
  (:goal (and (xpos n4) (ypos n4)))
  (:goal-reward 1000)
  (:metric maximize (reward))
)
