(define (problem rect-7-7-4-3-3)
  (:domain rectangle-world)
  (:objects n0 n1 n2 n3 n4 n5 n6 - int)
  (:init (xpos n0)
	 (ypos n0)
         (next n0 n1)
         (next n1 n2)
         (next n2 n3)
         (next n3 n4)
         (next n4 n5)
         (next n5 n6)
	 (safeX n0)
	 (safeX n4)
	 (safeX n5)
	 (safeY n0)
	 (safeY n1)
	 (safeY n6)
  )
  (:goal (and (xpos n6) (ypos n6)))
  (:goal-reward 1000)
  (:metric maximize (reward))
)
