(define (problem rect-7-7-3-4-4)
  (:domain rectangle-world)
  (:objects n0 n1 n2 n3 n4 n5 n6 - int)
  (:init (xpos n0)
	 (ypos n0)
         (next n0 n1)
         (next n1 n2)
         (next n2 n3)
         (next n3 n4)
         (next n4 n5)
         (next n5 n6)
	 (safeX n0)
	 (safeX n3)
	 (safeX n6)
	 (safeY n0)
	 (safeY n1)
	 (safeY n2)
	 (unsafe n0 n0)
	 (unsafe n0 n3)
	 (unsafe n0 n6)
	 (unsafe n1 n4)
	 (unsafe n2 n0)
	 (unsafe n2 n5)
	 (unsafe n3 n1)
	 (unsafe n3 n2)
	 (unsafe n3 n3)
	 (unsafe n3 n5)
	 (unsafe n4 n2)
	 (unsafe n4 n6)
	 (unsafe n5 n1)
	 (unsafe n5 n2)
	 (unsafe n5 n3)
	 (unsafe n6 n2)
	 (unsafe n6 n5)
  )
  (:goal (and (xpos n6) (ypos n6)))
  (:goal-reward 1000)
  (:metric maximize (reward))
)
