(define (problem prob_bw_4_n4_s4)
  (:domain prob_bw)
  (:objects b1 b2 b3 b4 - block)
  (:init (emptyhand) (on b1 b4) (on-table b2) (on b3 b1) (on b4 b2) (clear b3))
  (:goal (and (emptyhand) (on-table b1) (on b2 b3) (on b3 b4) (on b4 b1) (clear b2)))
)
