(define (problem prob_bw_5_n5_s1)
  (:domain prob_bw)
  (:objects b1 b2 b3 b4 b5 - block)
  (:init (emptyhand) (on b1 b4) (on-table b2) (on b3 b2) (on b4 b5) (on-table b5) (clear b1) (clear b3))
  (:goal (and (emptyhand) (on b1 b5) (on b2 b4) (on b3 b2) (on-table b4) (on-table b5) (clear b1) (clear b3)))
)
