(define (problem prob_bw_7_n7_s3)
  (:domain prob_bw)
  (:objects b1 b2 b3 b4 b5 b6 b7 - block)
  (:init (emptyhand) (on-table b1) (on b2 b5) (on b3 b6) (on-table b4) (on-table b5) (on b6 b7) (on b7 b4) (clear b1) (clear b2) (clear b3))
  (:goal (and (emptyhand) (on b1 b4) (on b2 b6) (on-table b3) (on-table b4) (on b5 b2) (on b6 b1) (on-table b7) (clear b3) (clear b5) (clear b7)))
)
