(define (problem prob_bw_5_n5_s2)
  (:domain prob_bw)
  (:objects b1 b2 b3 b4 b5 - block)
  (:init (emptyhand) (on b1 b3) (on b2 b1) (on b3 b5) (on-table b4) (on b5 b4) (clear b2))
  (:goal (and (emptyhand) (on b1 b4) (on b2 b5) (on b3 b1) (on b4 b2) (on-table b5) (clear b3)))
)
