(define (problem prob_bw_5_n5_s5)
  (:domain prob_bw)
  (:objects b1 b2 b3 b4 b5 - block)
  (:init (emptyhand) (on b1 b4) (on-table b2) (on b3 b5) (on-table b4) (on b5 b1) (clear b2) (clear b3))
  (:goal (and (emptyhand) (on b1 b2) (on-table b2) (on b3 b5) (on-table b4) (on b5 b4) (clear b1) (clear b3)))
)
