(define (problem prob_bw_6_n6_s5)
  (:domain prob_bw)
  (:objects b1 b2 b3 b4 b5 b6 - block)
  (:init (emptyhand) (on b1 b3) (on b2 b5) (on-table b3) (on b4 b6) (on-table b5) (on b6 b2) (clear b1) (clear b4))
  (:goal (and (emptyhand) (on b1 b6) (on b2 b5) (on b3 b2) (on-table b4) (on b5 b1) (on-table b6) (clear b3) (clear b4)))
)
