(define (problem prob_bw_5_n5_s4)
  (:domain prob_bw)
  (:objects b1 b2 b3 b4 b5 - block)
  (:init (emptyhand) (on b1 b3) (on b2 b4) (on-table b3) (on b4 b1) (on b5 b2) (clear b5))
  (:goal (and (emptyhand) (on-table b1) (on-table b2) (on b3 b4) (on b4 b5) (on b5 b2) (clear b1) (clear b3)))
)
