(define (problem prob_bw_6_n6_s1)
  (:domain prob_bw)
  (:objects b1 b2 b3 b4 b5 b6 - block)
  (:init (emptyhand) (on-table b1) (on b2 b3) (on-table b3) (on b4 b2) (on b5 b6) (on-table b6) (clear b1) (clear b4) (clear b5))
  (:goal (and (emptyhand) (on b1 b5) (on b2 b6) (on-table b3) (on b4 b2) (on b5 b4) (on-table b6) (clear b1) (clear b3)))
)
