(define (problem prob_bw_7_n7_s1)
  (:domain prob_bw)
  (:objects b1 b2 b3 b4 b5 b6 b7 - block)
  (:init (emptyhand) (on-table b1) (on-table b2) (on b3 b4) (on-table b4) (on b5 b3) (on b6 b1) (on-table b7) (clear b2) (clear b5) (clear b6) (clear b7))
  (:goal (and (emptyhand) (on-table b1) (on-table b2) (on b3 b4) (on b4 b5) (on-table b5) (on b6 b3) (on b7 b6) (clear b1) (clear b2) (clear b7)))
)
