(define (problem ex-bw-train-n08-s05-r107808)
  (:domain exploding-blocksworld)
  (:objects b1 b2 b3 b4 b5 b6 b7 b8 - block)
  (:init (emptyhand) (on-table b1) (on-table b2) (on b3 b2) (on b4 b5) (on b5 b3) (on b6 b1) (on-table b7) (on b8 b4) (clear b6) (clear b7) (clear b8) (no-detonated b1) (no-destroyed b1) (no-detonated b2) (no-destroyed b2) (no-detonated b3) (no-destroyed b3) (no-detonated b4) (no-destroyed b4) (no-detonated b5) (no-destroyed b5) (no-detonated b6) (no-destroyed b6) (no-detonated b7) (no-destroyed b7) (no-detonated b8) (no-destroyed b8) (no-destroyed-table))
  (:goal (and (on b1 b6) (on-table b2) (on b3 b2) (on b4 b1) (on b5 b8) (on-table b6) (on b7 b4) (on b8 b3)  )
)
)
