(define (problem sysadmin-6-3-3)
  (:domain sysadmin-slp)
  (:objects comp0 comp1 comp2 comp3 comp4 comp5 - comp)
  (:init
	 (conn comp0 comp1)
	 (conn comp0 comp2)
	 (conn comp0 comp3)
	 (conn comp1 comp2)
	 (conn comp2 comp3)
	 (conn comp3 comp4)
	 (conn comp3 comp5)
	 (conn comp4 comp5)
	 (conn comp5 comp0)
  )
  (:goal (forall (?c - comp)
                 (up ?c)))
  (:goal-reward 500)
 (:metric maximize (reward))
)
